services:
  api:
    build:
      context: ./api
    environment:
      - API_PORT=${API_PORT}
      - AISSTREAM_API_KEY=${AISSTREAM_API_KEY}
      - AISSTREAM_API_URL=${AISSTREAM_API_URL}
      - FORCE_COLOR=${FORCE_COLOR}
      - WAIT_TIME=${WAIT_TIME}
    ports:
      - 3000:3000

  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_MAPBOX_API_KEY=${VITE_MAPBOX_API_KEY}
        - VITE_MAPBOX_STYLE_URL=${VITE_MAPBOX_STYLE_URL}
    depends_on:
      - api
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - 80:80
